resultAnalysis/account/urls.py
from django.conf.urls import url, include
from .views import (
	login_view,
	account_view,
	logout_view,
	)
urlpatterns = [
    url(r'^login/$',login_view,name="login"),
    url(r'^logout/$',logout_view,name='logout'),
    url(r'^$',account_view,name='account'),
    ]

resultAnalysis/result/api/urls.py
from django.conf.urls import url
from .views import (
	ContactUsCreateAPIView,
	ReportErrorCreateAPIView,
	ReportBugCreateAPIView,
	)

urlpatterns = [
    url(r'^contact/$',ContactUsCreateAPIView.as_view(),name="contact"),
    url(r'^reportbug/$',ReportErrorCreateAPIView.as_view(),name="reportBug"),
    url(r'^reporterror/$',ReportBugCreateAPIView.as_view(),name="reportError"),
]
  

resultAnalysis/result/urls.py
from django.conf.urls import url

from .views import (
	getNewResult,
	getSessionAndsemester,
	showSemesterResult,
	showSubjectMarks,
	studentSemesterResult,
	contactUs,
	reportError,
	reportBug,
	)

urlpatterns=[
	url(r'^$',getSessionAndsemester,name='home'),
	url(r'^addnewrollno/$',getNewResult,name='newResult'),
	url(r'^contact/$',contactUs,name='contact'),
	url(r'^report/error/$',reportError,name='reporterror'),
	url(r'^report/bug/$',reportBug,name='reportbug'),
	url(r'^results/(?P<college>[\w|\W]+)/(?P<branch>[\w|\W]+)/(?P<yearOfJoining>[\w|\W]+)/(?P<semester>[\w|\W]+)/(?P<subjectCode>[\w|\W]+)/$',showSubjectMarks,name='subjectMarks'),
	url(r'^results/(?P<college>[\w|\W]+)/(?P<branch>[\w|\W]+)/(?P<yearOfJoining>[\w|\W]+)/(?P<semester>[\w|\W]+)/$',showSemesterResult,name='semesterResult'),
	url(r'^result/(?P<rollNo>\d+)/(?P<semester>\d+)/$',studentSemesterResult,name='studentSemesterResult'),
]

resultAnalysis/resultAnalyser/urls.py
from django.conf.urls import url

from .views import(
	studentResulAnalysis,
	compareResult,
	)

urlpatterns = [
	url(r'^student/(?P<rollNo>\d+)/$',studentResulAnalysis,name='studentResulAnalysis'),
	url(r'^student/$',studentResulAnalysis,name='studentResulAnalysisform'),
	url(r'^compare/$',compareResult,name="compare"),
]

resultAnalysis/resultAnalysis/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/',include('resultAnalyser.api.urls',namespace='api-analysis')),
    url(r'^newapi/',include('result.api.urls',namespace='newapi-analysis')),
    url(r'^analysis/',include('resultAnalyser.urls',namespace='analysis')),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^',include('result.urls',namespace='result')),
    url(r'^xlsx/',include('xlsx.urls',namespace='xlsx')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resultAnalysis/xlsx/urls.py
from django.conf.urls import url

from .views import (
	semseterResultxlsx,
	)

urlpatterns=[
	url(r'^semester-xlsx/(?P<collegeCode>\d+)/(?P<branchCode>\d+)/(?P<yearOfJoining>\d+)/(?P<semester>\d+)/$',semseterResultxlsx,name='semseterResultxlsx')
]

resultAnalysis/result/forms.py
from django import forms
from .models import (
	College,
	Branch,
	Course,
	TotalMarks,
	Subject,
	Student,
	Marks,
	)

class UrlForm(forms.Form):
	url = forms.URLField(widget=forms.URLInput(attrs={'class':'validate','id':'url'}))

	# DOING FROMS VAILDATIONS
	def clean_url(self,*args,**kwargs):
		url=self.cleaned_data.get('url')
		if not url[0:40]=='https://erp.aktu.ac.in/WebPages/OneView/':
			raise forms.ValidationError("INVALID URL!! Please enter a valid URL")
		return url

class SessionForm(forms.Form):
	# VALUE FOR CHOISE FIELDS
	semester=[(str(i),str(i)) for i in range(1,9)]

	# FORMS FIELDS 
	yearOfJoining = forms.ChoiceField(choices=Student.objects.values_list('yearOfJoining','yearOfJoining').distinct().order_by('yearOfJoining'))
	semester = forms.ChoiceField(choices=semester,required=True)
	college = forms.ModelChoiceField(queryset=College.objects.all().order_by('collegeCode'),empty_label="Select College")
	branch = forms.ModelChoiceField(queryset=Branch.objects.all().order_by('branchCode'),empty_label="select Branch")

## ORDERING FORM FOR RESULT
class OrderForm(forms.Form):
	choices=(
		('student__rollNo','Student Name'),
		('-internal','Internal Marks'),
		('-external','External Marks'),
		('-totalMarks','Total Marks')
		)
	order_by = forms.ChoiceField(choices=choices,required=False)

resultAnalysis/result/api/views.py
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK,HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from result.models import ContactUs,ReportBug,ReportError
from .serializer import (
	ContactUsSerializer,
	ReportBugSerializer,
	ReportErrorSerializer,
	)

class ContactUsCreateAPIView(CreateAPIView):
	queryset = ContactUs.objects.all()
	serializer_class = ContactUsSerializer

class ReportErrorCreateAPIView(CreateAPIView):
	queryset = ReportBug.objects.all()
	serializer_class = ReportBugSerializer

class ReportBugCreateAPIView(CreateAPIView):
	queryset = ReportError.objects.all()
	serializer_class = ReportErrorSerializer

resultAnalysis/result/views.py
import requests
from bs4 import BeautifulSoup

from django.db.models import Avg, Max, Min
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import (
	UrlForm,
	SessionForm,
	OrderForm,
	)

from .models import (
	College,
	Branch,
	Course,
	TotalMarks,
	Subject,
	Student,
	Marks,
	)


def contactUs(request):
	return render(request,'contact.html',{})

def reportError(request):
	return render(request,'reporterror.html',{})

def reportBug(request):
	return render(request,'reportbug.html',{})
	
def getNewResult(request):
	urlForm =UrlForm(request.POST or None)
	successText = ""
	errorMessage=""
	if request.method == "POST":
		if urlForm.is_valid():
			url=urlForm.cleaned_data.get('url')
			try:
				name = getResult(url)
				successText = name+" is succefully added"
			except Exception as ex:
				print (ex)
				errorMessage = "Unexpected Error Occured. Please submit your Roll number and URL in Report the Error page"
			# try:
			# 	getResult(url)
			# except:
			# 	raise Http404("not vaild rollno")
	content={
		'title':'NEW RESULT',
		'form':urlForm,
		'success':successText,
		'error':errorMessage
	}
	return render(request,'addNewResult.html',content)

def getSessionAndsemester(request):
	sessionForm = SessionForm(request.POST or None)
	if request.method == "POST":
		if sessionForm.is_valid():
			session=sessionForm.cleaned_data.get('yearOfJoining')
			print("------------------",session)
			semester=sessionForm.cleaned_data.get('semester')
			college=sessionForm.cleaned_data.get('college')
			branch=sessionForm.cleaned_data.get('branch')
			url_r="/results/%s/%s/%s/%s/"%(college,branch,session,semester)
			return HttpResponseRedirect(url_r)
			## SAVE SESSION AND SEMESTER IN USER SESSION FIELD THEN REDIRECT RESULT PAGE	
	content={
		'title':'HOME',
		'form':sessionForm,
	}
	return render(request,'home.html',content)

## GETING RESULT OF SEMESTER AND COLLEGE BASED
def showSemesterResult(request,college,branch,yearOfJoining,semester):
	collegeObjects=get_object_or_404(College, collegeName= college)
	branchObjects=get_object_or_404(Branch,branchName=branch)
	results=TotalMarks.objects.filter(student__college=collegeObjects,student__branchCode=branchObjects,\
		student__yearOfJoining=yearOfJoining,semester=semester).order_by('student__name')

	# GETTING ALL SUBJECT LIST FOR SUBJECT OPTIONS
	subjects=Marks.objects.filter(student=results[0].student, subjectCode__semester=semester)

	content={
		'title':'Result of Students',
		'results':results,
		'subjects':subjects,
	}
	return render(request,'result.html',content)

## VIEW FOR SUBJECT WISE MARKS 
def showSubjectMarks(request,college,branch,yearOfJoining,semester,subjectCode):
	collegeObjects=get_object_or_404(College, collegeName= college)
	branchObjects=get_object_or_404(Branch,branchName=branch)
	subjectObject=get_object_or_404(Subject,subjectCode=subjectCode,semester=semester,branchCode=branchObjects)
	results=Marks.objects.filter(student__college=collegeObjects,student__branchCode=branchObjects,\
		student__yearOfJoining=yearOfJoining,subjectCode=subjectObject).order_by('student__name')

	# GETTING ALL SUBJECT LIST FOR OPTIONS
	subjects=Marks.objects.filter(student=results[0].student, subjectCode__semester=semester)
	
	aggregations = results.filter(internal__gte = 0, external__gte=0,totalMarks__gte=0).aggregate(Avg('internal'),Max('internal'),Min('internal'),Avg('external'),Max('external'),Min('external'),Avg('totalMarks'),Max('totalMarks'),Min('totalMarks'))
	content={
		'title':'Result of Students',
		'results':results,
		'subjects':subjects,
		'subjectCode':subjectCode,
		'aggregations':aggregations,
	}
	return render(request,'result.html',content)

def studentSemesterResult(request,rollNo,semester):
	student =get_object_or_404(Student,rollNo=rollNo)
	subjectCodes=Subject.objects.filter(branchCode=student.branchCode,semester=semester)
	marks=Marks.objects.filter(student=student,subjectCode__in=subjectCodes)
	content={
		'student':student,
		'marks':marks,
	}
	return render(request,'semesterResult.html',content)


###  CODE FOR SCRAP RESULT 

def getResult(url):
	user_agent = {'User-agent': 'Mozilla/5.0'}
	req=requests.get(url,headers = user_agent)
	soup=BeautifulSoup(req.content,'html.parser')

	# FIND GENRAL DETAILS OF USER
	collegeCode=(((soup.find(id='lblInstitute').text).split('(')[1]).split(')')[0]).strip()
	collegeName=(soup.find(id='lblInstitute').text).strip()
	courseCode=((soup.find(id='lblCourse').text).split('(')[1]).split(')')[0]
	courseName=(soup.find(id='lblCourse').text).strip()
	branchCode=((soup.find(id='lblBranch').text).split('(')[1]).split(')')[0]
	barnchName=(soup.find(id='lblBranch').text).strip()
	#print(int(branchCode),barnchName)

	## NOW CHECKING UNIVERSAL DETAILS OF STUDENTS
	collegeObjects=College.objects.get_or_create(collegeCode=int(collegeCode),collegeName=collegeName)
	courseObjects=Course.objects.get_or_create(courseCode=int(courseCode),courseName=courseName)
	#print(courseObjects[0])
	branchObjects=Branch.objects.get_or_create(course=courseObjects[0],branchCode=int(branchCode),branchName=barnchName)

	rollNo=(soup.find(id='lblRollNo').text).strip()
	enrollmentNo=soup.find(id='lblEnrollmentNo').text.strip()
	name=soup.find(id='lblFullName').text.strip()
	fatherName=soup.find(id='lblFatherName').text.strip()
	gender=soup.find(id='lblGender').text.strip()
	image=soup.find(id='imgphoto')['src'].strip()
	yearOfJoining=2000+int(rollNo[0:2])

	## IF STUDENT IS LATERAL THEN 
	lateral=soup.find(id='ctl03_lblSem').text.strip()
	if lateral == '3,4':
		print("------------------- lateral ------------------------ ")
		yearOfJoining-=1

	studentObject=Student.objects.get_or_create(
		rollNo=rollNo,
		yearOfJoining=yearOfJoining,
		college=collegeObjects[0],
		branchCode=branchObjects[0],
		name=name,
		image=image,
		url=url,
		fatherName=fatherName,
		)
	if not gender == "":
		studentObject[0].gender=gender
	studentObject[0].enrollmentNo=enrollmentNo
	studentObject[0].save()

	# FIND ALL RESULT TABLE  ID 
	tables=soup.find_all('table')
	for table in tables:
		tableId=table.get('id')
		if tableId:

			# IF TABLE CONTAIN RESULT TABLE 
			if tableId.split('_')[-1:][0]=='grdViewSubjectMarksheet':

				# THEN FIND GENRAL DETAIL LIKE SEM AND TOTAL SUBJECT
				coreId=tableId.split('_')
				topId=coreId[0]+'_'+coreId[1]+'_'
				semester=(soup.find(id=topId+'lblSemesterId').text).strip()
				# print("semesterId = ",semester)
				if semester !='0':
					totalSubject=int((soup.find(id=topId+'lblTotalSubjectsCount').text).strip())
					totalMarks=(soup.find(id=topId+'lblSemesterTotalMarksObtained').text).strip()
					totalInternal=0
					totalExternal=0
					SemesterResultStatus = "PASS"

					# NOW GETTING SEMESTER SUBJECT MARKS 
					for i in range(0,totalSubject):
						subjectCode=(soup.find(id=tableId+'_subCode_'+str(i)).text).strip()
						subjectName=(soup.find(id=tableId+'_subName_'+str(i)).text).strip()
						subjectType=(soup.find(id=tableId+'_subType_'+str(i)).text).strip()

						## CREATE OR GET SUBJECT OBJECT
						subjectObject= Subject.objects.get_or_create(
							subjectCode = subjectCode,
							branchCode=branchObjects[0],
							)
						if subjectObject[1]:
							subjectObject[0].semester=semester
							subjectObject[0].subjectName=subjectName
							subjectObject[0].subjectType=subjectType
							subjectObject[0].save()

						# FIND MARKS 
						parentTd=(soup.find(id=tableId+'_subCode_'+str(i))).parent.parent
						allTd=parentTd.find_all('td')
						subjectInternal=allTd[3].text.strip()
						subjectExternal=allTd[4].text.strip()
						backMarks=allTd[5].text.strip()
						subjectCredit=allTd[6].text.strip()
						backStatus = False

						## IF SUBJECT MARKS AND BACK STATUS NOT ABLABE THEN 
						try:
							i=int(subjectInternal)
						except:
							subjectInternal='-1'

						try:
							i=int(subjectExternal)
						except:
							subjectExternal='-1'

						try:
							backMarks=backMarks.replace('*','')
							i=int(backMarks)
						except:
							backMarks='-1'

						try:
							if subjectCredit=='0' or subjectCredit == 'F':
								backStatus=True
								SemesterResultStatus = "COP"
						except:
							backStatus=False
							

						## SAVING SUBJECT STUDENTS MARKS 
						marksObject=Marks.objects.get_or_create(
							student=studentObject[0],
							subjectCode=subjectObject[0],
							)
						marksObject[0].internal=subjectInternal
						marksObject[0].external=subjectExternal
						if marksObject[0].backMarks<int(backMarks):
							marksObject[0].backMarks=backMarks
						else:
							backMarks=marksObject[0].backMarks
						marksObject[0].backStatus=backStatus
						print(subjectCode,subjectInternal,subjectExternal,backMarks)

						## GETTING TOTALINTERNAL AND EXTERNAL MARKS
						if backMarks=='-1':
							backMarks='0'
						if subjectInternal=='-1':
							subjectInternal='0'
						if subjectExternal=='-1':
							subjectExternal='0'

						# SAVE SUBJECT MARKS 
						marksObject[0].totalMarks=int(subjectInternal)+int(subjectExternal)
						marksObject[0].save()

						if subjectType !='CA':
							if subjectType =='Theory':
								totalInternal+=int(subjectInternal)
								totalExternal+=max(int(subjectExternal),int(backMarks))
							elif subjectType == 'Practical':
								totalInternal+=(max(int(subjectExternal),int(backMarks))+int(subjectInternal))
							elif subjectType == 'GP':
								totalInternal+=int(subjectInternal)


					# print(subjectCode,subjectName,subjectType,subjectInternal,subjectExternal)

					# SAVING AND UPDATING TOTAL MARKS OF RESULT 
					totalObjects,p=TotalMarks.objects.get_or_create(
						student=studentObject[0],
						semester=semester,
						)
					totalObjects.internal=totalInternal
					totalObjects.external=totalExternal
					totalObjects.totalMarks=totalInternal+totalExternal
					totalObjects.resultStatus=SemesterResultStatus
					totalObjects.save()
	return name	

resultAnalysis/templates/base.html
{% load staticfiles %}
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>{% block title %}{% endblock %} | RESULT ANALYSIS</title>
      <link rel="icon" href="/media/img/logo.jpg" type="image/jpg" sizes="16x16">
      <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
      {% block header %}
      {% endblock %}
   </head>
   <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
      <ul class="side-nav" id="mobile-nav">
         <li><a href="{% url 'result:home' %}">Home</a></li>
         <li><a href="{% url 'analysis:studentResulAnalysisform' %}">My Analysis</a></li>
         <li><a href="{% url 'analysis:compare' %}">Compare</a></li>
         <li><a href="{% url 'result:newResult' %}">Add New Result</a></li>
         <div class="divider"></div>
         <li><a href="{% url 'result:reporterror' %}">Report Error</a></li>
         <li><a href="{% url 'result:contact' %}">Contact Us</a></li>
         <div class="divider"></div>
    
      </ul>
      <div class="navbar-fixed">
         <nav class="white nav">
            <div class="nav-wrapper container">
               <a href="/"><img src="/media/img/logo.jpg"
                  height="100%;" class="hide-on-med-and-down" style="padding: 5px;">
                  </a>
               <a href="/" class="brand-logo">Result Analysis</a>
               <a href="#" data-activates="mobile-nav" class="button-collapse"><i class="material-icons">menu</i></a>
               <ul class="right hide-on-med-and-down">
                  <li><a href="{% url 'result:home' %}">Home</a></li>
                  <li><a href="{% url 'analysis:studentResulAnalysisform' %}">My Analysis</a></li>
                  <li><a href="{% url 'analysis:compare' %}">Compare</a></li>
                  <li><a href="{% url 'result:newResult' %}">Add New Result</a></li>
                  <li><a href="{% url 'result:reporterror' %}">Report Error</a></li>
               </ul>
            </div>
         </nav>
      </div>
      <main>
         {% block content %}
         {% endblock %}
      </main>

      <footer id="footer" class="my-footer page-footer hide-on-med-only hide-on-small-only grey">
         <div class="container">
            <div class="row">
               <div class="col l6 s12">
                  <h5 class="white-text">Result Analysis</h5>
                  <p class="grey-text text-lighten-4">Result Analysis is the initiative taken by the students of FGIET, Raerbareli. Result Analysis provides the ranking of students by internal marks, external marks, and total marks. It also helps student to analyze their result.</p>
                  <div class="fb-like" data-href="https://www.facebook.com/fgietResult/" data-width="450" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
               </div>

               <div class="col l4 offset-l2 s12">
                  <h5 class="white-text">Links</h5>
                  <ul>
                     <li><a class="grey-text text-lighten-3" href="#!">Home</a></li>
                     <li><a class="grey-text text-lighten-3" href="{% url 'result:reporterror' %}">Report error in result</a></li>
                     <li><a class="grey-text text-lighten-3" href="{% url 'result:contact' %}">Contact Us</a></li>
                     <li><a class="grey-text text-lighten-3" href="#!">Report Bug</a></li>
                     {% if user.is_authenticated %}
                     <li><a class="grey-text text-lighten-3" href="{% url 'account:logout' %}">logout</a></li>
                     {% else %}
                     <li><a class="grey-text text-lighten-3" href="{% url 'account:login' %}">login</a></li>
                     {% endif %}
                  </ul>
               </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="container">
               © 2015 resultanalysis.in
               <a class="grey-text text-lighten-4 right" href="#!">About us  </a>
            </div>
         </div>
      </footer>
      <!-- <div class="fb-like hide-on-large-only" data-href="https://www.facebook.com/fgietResult/" data-width="250" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div> -->
      
      <div class="hide-on-large-only grey mobile-footer my-footer">
      <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
         <p>made with <img src="/media/img/heart.svg" height="25px"> by resultanalysis.in</p>
      </div>
      <!-- Latest compiled and minified JavaScript -->
      <script src="{%static 'js/shuffle.js'%}"></script>
      <script>
         $(document).ready(function () {
             $(".button-collapse").sideNav();
             })
      </script>
      {% block js %}
      {% endblock %}
   </body>
</html>

resultAnalysis/templates/compareForm.html
{% extends "base.html" %}
{% block title %}{{ title  }}{% endblock %}
{% block content %}
<br/>
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="card">
      <div class="card-content" style="padding-bottom: 0px">
        <span class="card-title">Compare Your Result</span>
        <div class="row">
        <form action="" method="post" class="col s10 offset-s1">
           {% csrf_token %}
            <div class="row">
            <span style="color: red">{{ form.non_field_errors }}</span>
              <div class="input-field col s12 m6">
                  {{ form.baseStudent }}
                  <label for="baseStudent" data-error="Please Correct the Roll No">   1st Student Roll No.</label>
                  <span style="color: red">{{ form.baseStudent.errors }}</span>
              </div>
              <div class="input-field col s12 m6">
                {{ form.otherStudent }}
                <label for="otherStudent" data-error="Please Correct the Roll No" >2nd Student Roll No.</label>
                  <span style="color: red">{{ form.otherStudent.errors }}</span>
              </div>
            </div>
            <center><button class="waves-effect waves-blue btn center">Compare</button></center>
          </form>
        </div>
        {% if form.baseStudent.errors or  form.otherStudent.errors %}
        <div class="card-action">
              <a href="{% url 'result:newResult' %}" style="color: teal">Click here to add new Roll No.</a>
            </div>
        {% endif %}
    </div>
  </div>
</div>
</div>
{% endblock %}

{% block js %}

{% endblock %}

resultAnalysis/templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Contact Us{% endblock %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/contact.css' %}">
{% endblock %}
{% block content %}
<div class="row" style="margin-bottom:0px;padding-bottom:0px;">
   <div id="sendFeedback" class="section scrollspy row">
      <div class="container">
         <h3 class="center-align"><span>Send Us Feedback</span></h3>
         <form id="contactForm" class="col s12 l11">
         {% csrf_token %}
            <div class="row">
               <div class="input-field col l6 s12">
                  <i class="material-icons prefix">account_circle</i>
                  <input id="name" name="name" type="text" pattern="[a-z,A-Z,\s]{0,30}" class="validate">
                  <label for="name" data-error="looks like you misspelled your name">First Name</label>
               </div>
               <div class="input-field col l6 s12">
                  <i class="material-icons prefix">phone</i>
                  <input id="mobNo" name="mobNo" type="text" pattern="\d{10}" class="validate">
                  <label for="mobNo" data-error="Please correct your Phone no.">Telephone</label>
               </div>
               <div class="input-field col l12 s12">
                  <i class="material-icons prefix">email</i>
                  <input id="email" required name="email" type="email" class="validate">
                  <label for="email" data-error="Please correct your Email">Email*</label>
               </div>
               <div class="input-field col l12 s12">
                  <i class="material-icons prefix">mode_edit</i>
                  <textarea id="comment" name="comment" class="materialize-textarea" required></textarea>
                  <label for="comment" data-error="Please fill out this field">Comments</label>
               </div>
               <div class="input-field col s12">
                  <button type="submit" class="waves-effect waves-light btn col l2 offset-l10">
                  Send<i class="material-icons right">send</i>
                  </button>
               </div>
            </div>
         </form>
      </div>
   </div>
   <div id="reachus" class="section row" style="margin-bottom:0px;padding-bottom:0px;">
      <div class="conntainer">
         <h3 class="center-align"><span>Reach Us</span></h3>
         <h4 class="center-align flow-text">Feroze Gandhi Institute of Engineering &amp Technology</h4>
         <p class="flow-text center-align"><i class="material-icons prefix">email</i>&nbsp contactus@resultanalysis.in</p>
         <p class="flow-text center-align"><i class="material-icons prefix">phone</i>&nbsp Arpit Srivastava(9839468311)</p>
         <p class="flow-text center-align"><i class="material-icons prefix">phone</i>&nbspRohit P. Singh(9616886946)</p>
      </div>
      <div class="l12">
         <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7157.103813467643!2d81.2367350075756!3d26.243745478699886!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399ba1580a48a1b9%3A0x6d9caabf0668fa7f!2sFeroze+Gandhi+Institute+of+Engineering+%26+Technology!5e0!3m2!1sen!2sin!4v1487419292759" width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
   </div>
</div>

{% endblock %}
{% block js %}
<script>
$(document).ready(function () {
    $("#contactForm").submit(function(e){
        e.preventDefault()
        console.log($(this).serialize())
        $.ajax({
         method:"POST",
         url:"{%url 'newapi-analysis:contact' %}",
         data: $(this).serialize(),
         success: function(data){
            $("#contactForm").parent().html("<h3 class='flowtext'>Thankyou for your Feedback</h3>")
         },
         error: function(data){
            console.log(data)
         }
      })
    })
})
</script>
{% endblock %}